"""add_ai_suggestion_events_table

Revision ID: 2d4906a1b5bd
Revises: a3e74fd30f8a
Create Date: 2026-06-12 21:37:04.041680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4906a1b5bd'
down_revision: Union[str, Sequence[str], None] = 'a3e74fd30f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestion_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('suggested_domains', sa.JSON(), nullable=False),
    sa.Column('suggested_milestones', sa.JSON(), nullable=False),
    sa.Column('selected_domain', sa.String(length=100), nullable=True),
    sa.Column('selected_milestone_id', sa.Uuid(), nullable=True),
    sa.Column('max_similarity', sa.Float(), nullable=False),
    sa.Column('relevance_rank', sa.String(length=50), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_milestone_id'], ['milestones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestion_events_child_id'), 'ai_suggestion_events', ['child_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestion_events_created_at'), 'ai_suggestion_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_suggestion_events_interaction_type'), 'ai_suggestion_events', ['interaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_suggestion_events_interaction_type'), table_name='ai_suggestion_events')
    op.drop_index(op.f('ix_ai_suggestion_events_created_at'), table_name='ai_suggestion_events')
    op.drop_index(op.f('ix_ai_suggestion_events_child_id'), table_name='ai_suggestion_events')
    op.drop_table('ai_suggestion_events')
    # ### end Alembic commands ###
