"""observation_enum_and_soft_delete

Revision ID: 31e7376db48e
Revises: e5ecd7e79327
Create Date: 2026-06-11 23:38:49.379213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e7376db48e'
down_revision: Union[str, Sequence[str], None] = 'e5ecd7e79327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('observations', sa.Column('observer_relation', sa.String(length=100), nullable=True))
    op.add_column('observations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    sa_type = sa.Uuid() if hasattr(sa, 'Uuid') else sa.String(36)
    op.add_column('observations', sa.Column('deleted_by', sa_type, nullable=True))
    
    # Apply foreign key constraint check only for non-sqlite (Postgres)
    if op.get_bind().dialect.name != 'sqlite':
        op.create_foreign_key(
            'fk_observations_deleted_by_parents',
            'observations', 'parents',
            ['deleted_by'], ['id'],
            ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint('fk_observations_deleted_by_parents', 'observations', type_='foreignkey')
    op.drop_column('observations', 'deleted_by')
    op.drop_column('observations', 'deleted_at')
    op.drop_column('observations', 'observer_relation')
    op.drop_column('observations', 'location')
    # ### end Alembic commands ###
