"""create firsts table

Revision ID: cd8371253e10
Revises: 7c518dbe8b5b
Create Date: 2026-06-14 18:25:03.253857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8371253e10'
down_revision: Union[str, Sequence[str], None] = '7c518dbe8b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firsts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('is_first', sa.Boolean(), nullable=False),
    sa.Column('first_title', sa.String(length=255), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=False),
    sa.Column('linked_observation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_observation_id'], ['observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firsts_child_id'), 'firsts', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firsts_child_id'), table_name='firsts')
    op.drop_table('firsts')
    # ### end Alembic commands ###
